### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by colinking**
Resolves TSK-523

### CODE REVIEW

**Comment by colinking** [comment]
Current dependencies on/for this PR:
* main
  * **PR #139** <a href="https://app.graphite.dev/github/pr/airplanedev/node-sdk/139" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airplanedev/node-sdk/139?utm_source=stack-comment).

**Review by calufornia — APPROVED** [review]
🎉

**Comment by colinking** [comment]
Current dependencies on/for this PR:
* main
  * **PR #139** <a href="https://app.graphite.dev/github/pr/airplanedev/node-sdk/139" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airplanedev/node-sdk/139?utm_source=stack-comment).

**Comment by colinking** [comment]
Current dependencies on/for this PR:
* main
  * **PR #139** <a href="https://app.graphite.dev/github/pr/airplanedev/node-sdk/139" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airplanedev/node-sdk/139?utm_source=stack-comment).

**Pull request merged**
